name: scroll_snap_effect
description: A Flutter package to create easy scroll snap effect 
version: 0.0.2
homepage: https://github.com/farhanfadila1717/scroll_snap_effect
maintener: Farhan Fadila (@farhanfadila1717)

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
